### ISSUE TITLE
Run error, "ZeroDivisionError"

### ISSUE THREAD

**Issue by Cody2333** [GavinZhou2014/py-captcha-breaking#1]
博主好，我在跑你的demo的时候遇到了这个问题，不知道该如何解决
root@fa817dfe202e:~/temp/py-captcha-breaking# python demo.py | tee ./demo.log
Using Theano backend.
Start demo....
Networks initialization....
Initial network1....
Traceback (most recent call last):
  File "demo.py", line 427, in <module>
    main()
  File "demo.py", line 257, in main
    phase1_model = initial_num_char_phase1()
  File "demo.py", line 88, in initial_num_char_phase1
    model.add(Dense(input_dim=16*4*6, output_dim=256, init='glorot_uniform'))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/models.py", line 312, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/layers/core.py", line 695, in build
    name='{}_W'.format(self.name))
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg/keras/initializations.py", line 58, in glorot_uniform
    s = np.sqrt(6. / (fan_in + fan_out))
ZeroDivisionError: float division by zero

**Comment by iamGavinZhou** [comment]
I think problem is here "model.add(Dense(input_dim=1646, output_dim=256, init='glorot_uniform'))", input dim doesn't match

**Comment by hits-nlp** [comment]
I have the same problem (see issue #2527). Any solutions so far?
